### PR TITLE
Fixed : User settings shows uuids instead of names as sync attributes #968

### LINKED ISSUE #968: User settings shows uuids instead of names as sync attributes
### How to reproduce
- Go to App Designer
- Create a subject type
- In Registration Form of the subject, add a coded concept
- In the subject type's Advanced Settings -> Sync Concept, add the coded concept from the registration form
- Add a user. In sync settings, set the value of the coded concept to some valid answer of the coded concept
- View the user. Notice that the uuid of the attribute is shown, and not the name. 

It is important to show the name so that it is easier for users to understand the concept that has been set up. 

See attached image

Check the attached image. On the show page of a user (e.g. https://app.avniproject.org/#/admin/user/6690/show) , It is showing uuids of the concepts in the 'Sync settings for Subject Type: Individual' section instead of their current display values. This is not intuitive. We should fix this by displaying the display value e.g. 'Yes' and not '8ebbf088-f292-483e-9084-7de919ce67b7'

### PR DESCRIPTION
**Pull request by vedfordev**
# Notes :

Fixes #968

### Presupposition :
For user, it become easy if we shows concpet value in sync attribute.

### Tech Task :
1. Find related component **ConceptSyncAttributeShow** in user.js.
2. fetch answerconcept if **conceptUUID** is available.
3. Replaced uuid with name attribute.
   
### Dev Test :

**User with sync attribute:**
1. checked with (http://localhost:6010/#/admin/user/699/show)
2. reloading the page.
   
**User without sync attribute:**
1. checked page is not breaking

### Other Fixes:
As we can see there is no space between two skeleton of sync attribute. So I added margin

### Result : 
Screenshot 2023-11-28 at 9 25 14 AM

### CODE REVIEW

File: src/adminApp/user.js [hunk 1]
```diff
@@ -184,13 +184,22 @@ const ConceptSyncAttributeShow = ({ subjectType, syncAttributeName, ...props })
...
   if (isEmpty(conceptUUID)) return null;
+
+  const [valueMap, setValueMap] = useState(new Map());
+  useEffect(() => {
+    const newValMap = new Map();
+    ConceptService.getAnswerConcepts(conceptUUID).then(content =>
+      content.forEach(val => newValMap.set(val.id, val.name))
+    );
+    setValueMap(newValMap);
+  }, []);
```
Comment (vinayvenu) [inline src/adminApp/user.js]: 1. Since you are depending on a props value, you should declare it in the dependencies - https://react.dev/reference/react/useEffect#examples-dependencies
2. valueMap is a generic name. Add something more meaningful. eg: conceptSyncAttributeValues

**Review by vinayvenu — CHANGES_REQUESTED** [review]

**Review by vinayvenu — CHANGES_REQUESTED** [review]
Not sure of the purpose of the isMounted flag. How does it help? 
Why do you catch an error and ignore it?

**Comment by vedfordev** [comment]
@vinayvenu 
isMount flag is for handling unexpected behaviour of ui.
https://react.dev/reference/react/useEffect#updating-state-based-on-previous-state-from-an-effect

**Comment by vinayvenu** [comment]
@

> @vinayvenu
> 
>     1. isMount flag is for handling unexpected behaviour of ui.
>        https://react.dev/reference/react/useEffect#updating-state-based-on-previous-state-from-an-effect
> 
>     2. can I remove catch statement ?

Catch statement should be ignored only if you want to suppress the error. If not, then you should not do this at all.

**Review by himeshr — APPROVED** [review]
