### PR TITLE
#889 | Re rendering of OrgManger is fixed.

### LINKED ISSUE #889: Search issue - cursor gets out of focus
https://avni.freshdesk.com/a/tickets/2324

To reproduce --
1. Go to Web console
2. Go to Admin
3. Select Users from left hand panel
4. Try searching a user by some search string, as soon as we pause while adding the search string the cursor gets out of focus.

### PR DESCRIPTION
**Pull request by vedfordev**
## Tech Note :

Fixes #889 

#### Problem:
1. **OrgManager** Component is re rendering when we are typing in the input field. I find that in props location is causing the re render.
2. It create memory leak issue.

#### Task Done :
1. I added **shouldComponentUpdate** lifecycle method in **OrgManager** component.

#### Dev Testing :
1. checked with putting log in render and other lifecycle method.

### CODE REVIEW

File: src/adminApp/OrgManager.js [hunk 1]
```diff
@@ -50,6 +51,9 @@ class OrgManager extends Component {
   getChildContext() {
     return { store };
   }
+  shouldComponentUpdate(nextProps, nextState, nextContext) {
+    return !_.isEqual(_.omit(nextProps, ["location"]), _.omit(this.props, ["location"]));
```
Comment (himeshr) [inline src/adminApp/OrgManager.js:55]: Due to performance considerations, it would be better if we did a shallow compare within  shouldComponentUpdate().

**Comment by vedfordev** [comment]
@himeshr fixed using useContext.

**Review by himeshr — APPROVED** [review]
