### PR TITLE
Fixes #1145

### LINKED ISSUE #1145: Unable to see sync concept if it is not coded concept
**Describe the bug**
we made changes to show sync attribute values which was earlier shows as uuids. but currently for non coded concept it is not showing the value as screenshot

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to goonj organization
2. Open user who has sync attribute
3. See the user

**Expected behaviour**
Handle scenario for both coded and not coded sync attribute value.

**Screenshots**
Screenshot 2024-02-29 at 11 47 09 AM

### PR DESCRIPTION
**Pull request by vedfordev**
## Notes :

Fixes #1145 

### Tech Task done : 
1. Reduced the api calls to show coded sync attribute value.
2. Now working for text sync attribute.

### CODE REVIEW

File: src/adminApp/user.js [hunk 1]
```diff
@@ -452,19 +452,51 @@ const initialSyncAttributes = { subjectTypes: [] };
...
         anySubjectTypeDirectlyAssignable,
         anySubjectTypeSyncByLocation
       } = res.data;
       const sortedSubjectTypes = sortBy(subjectTypes, "id");
-      setSyncAttributesData({
-        subjectTypes: sortedSubjectTypes,
-        anySubjectTypeDirectlyAssignable,
-        anySubjectTypeSyncByLocation
+
+      const codedConceptUUIDSet = new Set();
```
Comment (himeshr) [inline src/adminApp/user.js:464]: Refactor and move into separate method

**Comment by vedfordev** [comment]
@himeshr changed the code suggested by you

**Review by himeshr — APPROVED** [review]
